### ISSUE TITLE
Convergence differences between lme4 and lmerTest

### ISSUE THREAD

**Issue by MalteHB** [KennethEnevoldsen/Tutorial-Power-Analysis-using-simr#2]
Me and my peers have discovered that when using the lmer() function with the package lmerTest our model fails to converge. However, when running the exact same model, this being the exact same lines of code with identical syntax, but specifying R to use the lmer() function from the package lme4, the model does converge. We have heard from a very special person that lmerTest and lme4 has the same backend and that lmerTest simply calls lme4. If this is the case it is fairly bizarre that we see different results when specifying one or the other package. So what is the actual case here, Kenneth?

**Comment by KennethEnevoldsen** [comment]
Code to reproduce please

According to the [lmertest paper](https://www.jstatsoft.org/article/view/v082i13/0) is it simply an expansion to lme4. It is probably more likely that it is a user error. Alternatively you can (and should according to the people behind lme4) use anova model comparison to compare against a **fair** null model to see whether your fixed/random effect provide improvements.

**Comment by MalteHB** [comment]
Here is the code. If you want the data you will have to contact me in private. 

```{r}
library(pacman)
p_load(tidyverse, lmerTest)
dod <- read_csv("merged_df.csv", col_types = cols(
  timesincestart = col_double(),
  participant = col_double(),
  StudyNum = col_double(),
  condition = col_character(),
  trial = col_double(),
  pairID = col_double(),
  changeHR_self = col_double(),
  changeHR_other = col_double(),
  changeResp_self = col_double(),
  changeResp_other = col_double(),
  HR_self = col_double(),
  HR_other = col_double(),
  Resp_self = col_double(),
  Resp_other = col_double(),
  group = col_double()
))
s4 <- filter(dod, StudyNum == 4) #Subsetting study 4
# Set the most interesting contrast e.g. by defining synchronous or conversation as the baseline
s4$condition <- relevel(as.factor(s4$condition), "Synchronous") #Synchronous is chosen as the baseline because it is the most basic condition. Because people speak at the same time. 
unique(s4$condition)
# Model change as a function of own and other previous state
p_load(lmerTest)
## The complex model failed to converge, and setting an arbitrary limit felt, well, arbitrary, therefore we resorted to simpler means by using simpler models. This will be the procedure for the rest of the assignment
#hrm1 <- lmer(changeHR_self ~ condition + 
#               (HR_self + HR_other) * condition +
#               ((HR_self + HR_other) * condition | participant) + 
#               ((HR_self + HR_other) * condition | group),
#             data=s4)
#summary(hrm1)

## SIMPLER MODELS
hrm1 <- lmer(changeHR_self ~
             0 + condition + (HR_self + HR_other) : condition +
             (0 + condition|participant) +
             (0 + condition|group),
             data = s4,
             REML = F)
summary(hrm1)

hrm2 <- lmer(changeHR_self ~
             (HR_self + HR_other) * condition +
             (condition|participant) +
             (condition|group),
             data = s4,
             REML = F)
summary(hrm2)

hrm3 <- lme4::lmer(changeHR_self ~
             (HR_self + HR_other) * condition +
             (condition|participant) +
             (condition|group),
             data = s4,
             REML = F)
summary(hrm3)
```

**Comment by KennethEnevoldsen** [comment]
Well without data it is quite hard to reproduce anything ;) Also I am not sure from what of the 3 models you have given me is the problem
1) Please short it down to to exactly the one model which causes the error
2) Feel free to send me the data however you like

**Comment by MalteHB** [comment]
1. 
```{r}
hrm2 <- lmer(changeHR_self ~
             (HR_self + HR_other) * condition +
             (condition|participant) +
             (condition|group),
             data = s4,
             REML = F)
summary(hrm2)
```
2. Okay. Here you go: 
https://we.tl/t-rJQ7ShJYKL

**Comment by KennethEnevoldsen** [comment]
Can see isSingular is called, which basically says you have too many effect given the data. [See the documentation](https://www.rdocumentation.org/packages/lme4/versions/1.1-21/topics/isSingular)
This should be a hint to disregard both models, it basically says you are extremely likely to overfit your data. 

That being said it seems like both models have converged without any warnings. See the ```convergence code: 0``` which according to the [documentation](https://cran.r-project.org/web/packages/lme4/lme4.pdf) means: *convergence code, equal to zero for successful convergence*
However it seems like the lmerTest prints the warning message ```Warning message:
Model failed to converge with 1 negative eigenvalue: -1.6e+03 ```
I would consider this a bug. I have raised a bug on their [GitHub](https://github.com/runehaubo/lmerTestR/issues/30) I suggest you go give it a thumbs up for faster response.

My results is down here:
```
> hrm2 <- lmerTest::lmer(changeHR_self ~
+                (HR_self + HR_other) * condition +
+                (condition|participant) +
+                (condition|group),
+              data = s4,
+              REML = F)
boundary (singular) fit: see ?isSingular
Warning message:
Model failed to converge with 1 negative eigenvalue: -1.6e+03 
> summary(hrm2)
Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite's method ['lmerModLmerTest']
Formula: changeHR_self ~ (HR_self + HR_other) * condition + (condition |      participant) + 

(...)

Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Correlation matrix not shown by default, as p = 15 > 12.
Use print(x, correlation=TRUE)  or
    vcov(x)        if you need it

convergence code: 0
boundary (singular) fit: see ?isSingular
```

```
> hrm2_lme4 <- lme4::lmer(changeHR_self ~
+                          (HR_self + HR_other) * condition +
+                          (condition|participant) +
+                          (condition|group),
+                        data = s4,
+                        REML = F)
boundary (singular) fit: see ?isSingular
> summary(hrm2_lme4)
Linear mixed model fit by maximum likelihood  ['lmerMod']
Formula: changeHR_self ~ (HR_self + HR_other) * condition + (condition |      participant) + 

(...)

Correlation matrix not shown by default, as p = 15 > 12.
Use print(x, correlation=TRUE)  or
    vcov(x)        if you need it

convergence code: 0
boundary (singular) fit: see ?isSingular
```
